import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Poster } from '@/components/poster/Poster';
import { Footer } from '@/components/footer/Footer';
import { Header } from '@/components/header/Header';
import { ConsultationModalProvider } from '@/components/consultation-modal';

import './globals.css';

const nunito = localFont({
  src: [
    {
      path: '../fonts/nunito-v31-latin-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/nunito-v31-latin-600.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={nunito.variable}>
        <ConsultationModalProvider>
          <Header />
          <Poster />
          <main>{children}</main>
          <Footer />
        </ConsultationModalProvider>
      </body>
    </html>
  );
}
